services:
  site:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: badminton_scoreboard
    restart: unless-stopped
    ports:
      - 8889:8080
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
